### ISSUE TITLE
Millenaire Crashes when placing down any type of villager

### ISSUE THREAD

**Issue by mattmodz** [Millenaire/Millenaire#13]
---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 1/9/18 5:59 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at org.millenaire.common.MLN.getParchment(MLN.java:811)
	at org.millenaire.common.item.ItemParchment.func_77659_a(ItemParchment.java:101)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:146)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78769_a(PlayerControllerMP.java:377)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1475)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1953)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at org.millenaire.common.MLN.getParchment(MLN.java:811)
	at org.millenaire.common.item.ItemParchment.func_77659_a(ItemParchment.java:101)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:146)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78769_a(PlayerControllerMP.java:377)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1475)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['D-REXMODDINGYT'/146, l='MpServer', x=-94.75, y=70.62, z=-279.40]]
	Chunk stats: MultiplayerChunkCache: 1089, 1098
	Level seed: 0
	Level generator: ID 04 - RWG, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,64,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 102254 game time, 6961 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 98 total; [EntityCow['Cow'/256, l='MpServer', x=-126.84, y=82.00, z=-212.16], EntityBat['Bat'/258, l='MpServer', x=-128.76, y=53.23, z=-203.94], EntityBat['Bat'/261, l='MpServer', x=-142.94, y=49.41, z=-206.00], MoCEntityFox['Fox'/262, l='MpServer', x=-128.72, y=81.00, z=-203.28], EntityBat['Bat'/268, l='MpServer', x=-120.25, y=39.49, z=-332.50], EntityPig['Pig'/269, l='MpServer', x=-127.81, y=82.00, z=-270.24], EntityPig['Pig'/270, l='MpServer', x=-123.50, y=82.00, z=-255.31], EntityCow['Cow'/271, l='MpServer', x=-126.69, y=81.00, z=-209.50], EntityCow['Cow'/272, l='MpServer', x=-127.88, y=81.00, z=-210.13], EntityBuggy['Buggy'/273, l='MpServer', x=-125.50, y=83.50, z=-204.50], EntityCreeper['Creeper'/275, l='MpServer', x=-109.97, y=16.00, z=-210.22], EntityCreeper['Creeper'/276, l='MpServer', x=-107.63, y=16.00, z=-212.06], EntitySpider['Spider'/277, l='MpServer', x=-110.19, y=16.00, z=-208.88], EntityPig['Pig'/278, l='MpServer', x=-105.16, y=84.00, z=-219.03], EntityBat['Bat'/288, l='MpServer', x=-68.53, y=25.10, z=-256.28], EntityZombie['Zombie'/289, l='MpServer', x=-81.50, y=31.00, z=-247.50], EntityCreeper['Creeper'/291, l='MpServer', x=-80.50, y=29.00, z=-219.50], EntityCreeper['Creeper'/292, l='MpServer', x=-82.50, y=29.00, z=-219.50], EntityZombie['Zombie'/293, l='MpServer', x=-84.38, y=57.00, z=-217.94], EntitySkeleton['Skeleton'/294, l='MpServer', x=-84.00, y=57.00, z=-216.94], EntityBat['Bat'/295, l='MpServer', x=-79.84, y=57.00, z=-212.56], EntityBat['Bat'/296, l='MpServer', x=-77.03, y=53.15, z=-203.44], EntitySkeleton['Skeleton'/297, l='MpServer', x=-90.50, y=35.00, z=-203.50], EntityCreeper['Creeper'/308, l='MpServer', x=-65.69, y=23.00, z=-349.69], EntityPig['Pig'/309, l='MpServer', x=-76.81, y=63.00, z=-318.53], EntityPig['Pig'/310, l='MpServer', x=-71.78, y=63.00, z=-309.81], EntityPig['Pig'/311, l='MpServer', x=-64.31, y=64.00, z=-309.53], EntityPig['Pig'/312, l='MpServer', x=-69.13, y=64.00, z=-302.50], EntityCreeper['Creeper'/313, l='MpServer', x=-66.38, y=16.00, z=-280.41], EntityCreeper['Creeper'/317, l='MpServer', x=-80.03, y=29.00, z=-217.50], EntityZombie['Zombie'/318, l='MpServer', x=-84.50, y=57.00, z=-215.97], EntitySkeleton['Skeleton'/319, l='MpServer', x=-77.50, y=57.00, z=-217.50], EntitySkeleton['Skeleton'/320, l='MpServer', x=-78.50, y=57.00, z=-220.50], EntityZombie['Zombie'/2371, l='MpServer', x=-111.50, y=34.00, z=-262.47], EntityZombie['Zombie'/2372, l='MpServer', x=-110.25, y=33.00, z=-260.50], EntitySkeleton['Skeleton'/2373, l='MpServer', x=-109.50, y=33.00, z=-259.50], EntityZombie['Zombie'/327, l='MpServer', x=-64.97, y=23.00, z=-348.50], EntityCreeper['Creeper'/328, l='MpServer', x=-57.47, y=23.00, z=-355.69], EntityZombie['Zombie'/329, l='MpServer', x=-60.44, y=24.00, z=-351.44], EntityZombie['Zombie'/330, l='MpServer', x=-58.03, y=24.00, z=-331.47], EntityBat['Bat'/2378, l='MpServer', x=-82.63, y=16.18, z=-243.44], EntityPig['Pig'/331, l='MpServer', x=-58.91, y=63.00, z=-304.97], EntityPig['Pig'/332, l='MpServer', x=-59.69, y=68.00, z=-292.50], EntitySkeleton['Skeleton'/333, l='MpServer', x=-50.50, y=24.00, z=-272.50], EntitySkeleton['Skeleton'/334, l='MpServer', x=-49.50, y=24.00, z=-268.50], EntityCreeper['Creeper'/335, l='MpServer', x=-62.44, y=11.00, z=-228.94], EntityZombie['Zombie'/336, l='MpServer', x=-49.53, y=19.00, z=-227.56], EntityPig['Pig'/337, l='MpServer', x=-57.97, y=79.00, z=-221.97], EntityZombie['Zombie'/339, l='MpServer', x=-37.56, y=44.35, z=-355.85], EntityChicken['Chicken'/340, l='MpServer', x=-37.56, y=44.00, z=-355.75], EntityZombie['Zombie'/2132, l='MpServer', x=-162.50, y=39.00, z=-339.50], EntityBat['Bat'/341, l='MpServer', x=-36.13, y=34.00, z=-341.59], EntityZombie['Zombie'/2133, l='MpServer', x=-164.50, y=39.00, z=-337.50], EntityCreeper['Creeper'/342, l='MpServer', x=-39.50, y=34.00, z=-345.50], EntityCreeper['Creeper'/343, l='MpServer', x=-46.50, y=43.00, z=-342.50], EntityCreeper['Creeper'/344, l='MpServer', x=-46.50, y=43.00, z=-343.50], EntityZombie['Zombie'/345, l='MpServer', x=-39.50, y=19.00, z=-334.50], EntityPig['Pig'/346, l='MpServer', x=-34.84, y=69.00, z=-292.56], EntityPig['Pig'/347, l='MpServer', x=-41.88, y=70.00, z=-282.22], EntityPig['Pig'/348, l='MpServer', x=-42.16, y=70.00, z=-283.44], EntityPig['Pig'/349, l='MpServer', x=-45.31, y=72.00, z=-275.50], EntityZombie['Zombie'/1885, l='MpServer', x=-161.50, y=39.00, z=-338.50], EntityPig['Pig'/350, l='MpServer', x=-44.31, y=78.00, z=-261.41], EntityCreeper['Creeper'/1888, l='MpServer', x=-33.50, y=26.00, z=-286.50], EntitySkeleton['Skeleton'/1890, l='MpServer', x=-109.50, y=33.00, z=-257.50], EntityCreeper['Creeper'/355, l='MpServer', x=-25.50, y=23.00, z=-334.50], EntityBat['Bat'/356, l='MpServer', x=-23.03, y=53.30, z=-292.94], EntityZombie['Zombie'/357, l='MpServer', x=-27.16, y=52.00, z=-293.28], EntitySpider['Spider'/358, l='MpServer', x=-28.41, y=52.00, z=-294.25], EntityBat['Bat'/359, l='MpServer', x=-20.47, y=54.33, z=-282.78], EntityPig['Pig'/360, l='MpServer', x=-22.06, y=71.00, z=-209.94], EntityPig['Pig'/361, l='MpServer', x=-23.03, y=70.00, z=-206.91], EntityPig['Pig'/363, l='MpServer', x=-24.53, y=69.00, z=-202.69], EntityPig['Pig'/364, l='MpServer', x=-20.84, y=67.00, z=-200.47], GCEntityClientPlayerMP['D-REXMODDINGYT'/146, l='MpServer', x=-94.75, y=70.62, z=-279.40], EntityBat['Bat'/219, l='MpServer', x=-173.47, y=36.00, z=-345.00], EntityBat['Bat'/220, l='MpServer', x=-173.31, y=36.00, z=-346.31], EntitySheep['Sheep'/221, l='MpServer', x=-161.66, y=71.00, z=-311.50], EntityCow['Cow'/222, l='MpServer', x=-161.31, y=73.00, z=-298.72], EntitySheep['Sheep'/223, l='MpServer', x=-169.94, y=72.00, z=-310.03], EntityCow['Cow'/224, l='MpServer', x=-166.75, y=79.00, z=-258.69], EntityCow['Cow'/226, l='MpServer', x=-173.31, y=77.00, z=-264.78], EntityCow['Cow'/227, l='MpServer', x=-155.75, y=87.00, z=-256.63], EntityBat['Bat'/228, l='MpServer', x=-173.00, y=33.29, z=-256.50], EntityCreeper['Creeper'/235, l='MpServer', x=-154.50, y=38.00, z=-356.50], EntityCow['Cow'/236, l='MpServer', x=-150.75, y=74.00, z=-325.63], EntityCow['Cow'/237, l='MpServer', x=-153.31, y=69.00, z=-329.75], EntitySheep['Sheep'/238, l='MpServer', x=-142.97, y=68.00, z=-333.88], EntitySkeleton['Skeleton'/239, l='MpServer', x=-145.50, y=43.00, z=-315.50], EntityCow['Cow'/240, l='MpServer', x=-152.69, y=69.00, z=-318.53], EntityCow['Cow'/241, l='MpServer', x=-147.63, y=72.00, z=-302.59], EntityCow['Cow'/242, l='MpServer', x=-150.50, y=83.00, z=-227.81], EntitySpider['Spider'/250, l='MpServer', x=-141.84, y=45.00, z=-341.59], EntitySpider['Spider'/251, l='MpServer', x=-139.00, y=44.00, z=-346.75], EntityCow['Cow'/252, l='MpServer', x=-138.19, y=67.00, z=-326.47], EntityCow['Cow'/253, l='MpServer', x=-141.38, y=71.00, z=-300.59], EntityBat['Bat'/254, l='MpServer', x=-135.69, y=17.65, z=-264.66], EntityZombie['Zombie'/255, l='MpServer', x=-135.50, y=61.00, z=-236.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:425)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_151, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 388269952 bytes (370 MB) / 882556928 bytes (841 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1024M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_D8 25 mods loaded, 25 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAA	cuchaz.ships.core{1.7.10-1.0.3} [Ships Mod Core] (minecraft.jar) 
	UCHIJAAAA	carsanddrives{1.0.9} [Cars and Drives] ([Minecraft-INSIDE.com] cars_and_drives_mod_v_1.0.9.jar) 
	UCHIJAAAA	BetterFoliage{2.0.14} [Better Foliage] (Better-Foliage-Mod-1.7.10.jar) 
	UCHIJAAAA	CoroAI{v1.0} [CoroAI] (CoroUtil-1.0.jar) 
	UCHIJAAAA	ExtendedRenderer{v1.0} [Extended Renderer] (CoroUtil-1.0.jar) 
	UCHIJAAAA	ConfigMod{v1.0} [Extended Mod Config] (CoroUtil-1.0.jar) 
	UCHIJAAAA	disastercraft{0.0.4.3} [Disaster Craft] (Disaster-Craft-Mod-1.7.10.jar) 
	UCHIJAAAA	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.497.jar) 
	UCHIJAAAA	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.497.jar) 
	UCHIJAAAA	ExtraPlanets{1.6.9} [ExtraPlanets] (Extra-Planets-Mod-1.7.10.jar) 
	UCHIJAAAA	instahouse{8.0} [Insta House] (Insta-House-Mod-1.7.10.jar) 
	UCHIJAAAA	journeymap{5.1.4p1} [JourneyMap] (JourneyMap-Mod-1.7.10-Unlimited.jar) 
	UCHIJAAAA	millenaire{6.0.1} [MillÃ©naire] (millenaire-6.0.1.jar) 
	UCHIJAAAA	mfs{6.0.1} [Minecraft Flight Simulator] (Minecraft Flight Simulator-1.7.10-6.0.1.jar) 
	UCHIJAAAA	MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod] (mo creatures 1.7.10.jar) 
	UCHIJAAAA	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) 
	UCHIJAAAA	stefinusguns{0.5.2} [New Stefinus Guns] (New-Stefinus-3D-Guns-Mod-1.7.10.jar) 
	UCHIJAAAA	RWG{Alpha 1.3.2} [Realistic World Gen Alpha] (RWG-alpha-1.3.2.jar) 
	UCHIJAAAA	cuchaz.cuchazinteractive{1.7.10-1.0} [Cuchaz Interactive] (shipsMod-v1.7.10-1.0.4.jar) 
	UCHIJAAAA	cuchaz.ships{1.7.10-1.0.3} [Ships Mod] (shipsMod-v1.7.10-1.0.4.jar) 
	UCHIJAAAA	weather2{v2.3.11} [Localized Weather & Storms] (weather2-1.7.10-2.3.10.jar) 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '3.3.11672 Compatibility Profile Context' Renderer: 'ATI Mobility Radeon HD 4200 Series'
	Launched Version: ForgeOptiFine 1.7.10
	LWJGL: 2.9.1
	OpenGL: ATI Mobility Radeon HD 4200 Series GL version 3.3.11672 Compatibility Profile Context, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
	OptiFine Version: OptiFine_1.7.10_HD_U_D8
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.3.11672 Compatibility Profile Context
	OpenGlRenderer: ATI Mobility Radeon HD 4200 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 2

**Comment by TheTrueColonel** [comment]
This is a known issue in the latest dev version. It'll be fixed soon.

**Comment by FireController1847** [comment]
Please report all crash reports in the Discord. This is for issues with the mod itself and _not_ crash reports (while that does have to do with the mod, it's not explaining the issue. Please keep all crash reports to the Discord for future reference. Thanks!
