### ISSUE TITLE
Internal building names and actual file names don't match

### ISSUE THREAD

**Issue by MoonCutter2B** [Millenaire/Millenaire#2]
Looks like the internal building names (from the json-file) is something like "normal:Egy..."
But the actual resource file for that building is "Egy..." (under assets/...)
I get a NPE when clickin gon the village stone.

**Comment by MoonCutter2B** [comment]
I added an ugly substring thingy and got it to work (i'm not a Java developer btw).
I think there is a method somewhere that should be used instead tp get the correct filename.

**Comment by TheTrueColonel** [comment]
If you know how to use Git, can you create a pull request with the fix, for the team to evaluate?

**Comment by 073TheBoss** [comment]
I'm not sure what's not working with the internal building name, everything seems to be working fine for me with that. However, I am getting the NPE when a VillageStone is generated and I'm looking into that now.
