### ISSUE TITLE
Crashing when joining server

### ISSUE THREAD

**Issue by niklas2233** [Millenaire/Millenaire#21]
**Please describe the issue you are having is as much detail as possible:**
its crashing the server when joining

**Describe how to be able to reproduce this bug:**
dont really know
 
Mod Version: 6.2.0 B2
Forge Version: 1.12.2-14.23.1.2587

- [ ] This issue is High Priority (Crashes the modpack, makes the mod unuseable)
- [x] I've tested this issue on the latest version of the mod for the latest version of Minecraft.

https://pastebin.com/KfAvCe1w

**Comment by SamboyCoding** [comment]
@Kinniken This one's your port. Not ours.

**Comment by SamboyCoding** [comment]
For reference that method is net.minecraft.network.play.server.SPacketCustomPayload.getBufferData() which returns a PacketBuffer.

**Comment by SamboyCoding** [comment]
aaand I've just realised you (Kinniken) have already posted on the forge forums. Ignore me.

**Comment by Kinniken** [comment]
Indeed, it's in fact already fixed on my side, though not yet released. Thanks for the mention.

@073TheBoss , you had told me you would update the readme in this repo to make it clear it is for the rewrite and not the existing code, could you do it? Without it we'll probably have more people ending up creating tickets here by mistake. Thanks.

**Comment by TheTrueColonel** [comment]
@Kinniken I'll get that updated in a bit.
