### ISSUE TITLE
NPC disapear

### ISSUE THREAD

**Issue by niklas2233** [Millenaire/Millenaire#22]
V 6.2.0 B4
F 14.23.1.2587

MP

So npc disapear when i go up to them and try to speak with them

**Comment by TheTrueColonel** [comment]
As stated before, and even put in the disclaimer, this bug tracker is not for Kinniken's port. You have been told this before.

**Comment by FireController1847** [comment]
As @TheTrueColonel stated, @niklas2233 this is not a bug report area for v6 and below, OR kinnikens port. Please report this on the forums or the Discord. Any further issues from you and they will be closed.
