### ISSUE TITLE
Crash when trying to trade with villager

### ISSUE THREAD

**Issue by Nexusdog** [Millenaire/Millenaire#23]
MC/F 1.12.2/2618

https://pastebin.com/nKLRbXC9

I tried to make sense of the crash report but yeah... apologies if it's not related to your mod guys.

**Comment by TheTrueColonel** [comment]
# Disclaimer

This repository is not for Kinniken's port to 1.12.2. Please discuss those errors on his forums. Any and all issues created for his port will be removed.

**Comment by TheTrueColonel** [comment]
# Disclaimer

**Comment by Kinniken** [comment]
As stated, this should get reported in the Millénaire forums.

In any case from the stack trace it seems to be a conflict with the "ItemScroller" mod. I'll note it, but I won't try and fix mod compatibility issues until Millénaire itself is stable.
