### ISSUE TITLE
i have performance problems on my Server [1.12.2]

### ISSUE THREAD

**Issue by Kocytos** [Millenaire/Millenaire#24]
I use the minecraft version 1.12.2 
mod version is: millenaire-6.2.0-alpha.5
my forge version is: 1.12.2-14.23.2.2611

i use this mod with other mods on my server and i don't have performance problems bevor i installed this mod and than i installed this mod and my performance is badly. 2 villages are aktiv and two player on my server and than perfomance is very badly. i don't know why but i hope it will be fixed..

**Comment by TheTrueColonel** [comment]
# DISCLAIMER
This repository is not for Kinniken's port to 1.12.2. Please discuss those errors [on his forums](http://millenaire.org/forum/viewforum.php?f=5&sid=e1b69037ba374473b92fbe9f34114cc1). Any and all issues created for his port will be removed.
