### ISSUE TITLE
License file is conflicting nonsense

### ISSUE THREAD

**Issue by mcmonkey4eva** [Millenaire/Millenaire#28]
**Please describe the issue you are having is as much detail as possible:**

The license file in this repo is nonsense.

False date claim: 2011 start date, when the repo goes back to 2013 and I'm not so sure it was considered to be under MIT that far back.

False authorship claim: `Visual Fire Development` and `http://millenaire.org/` are written together in a way that implies they are together presenting a single licensing claim (or that they are a single entity).

The ideal way to handle that portion of a license is to list the year(s) in which `http://millenaire.org/` was considered owner, and on a separate line list the year(s) `Visual Fire Development` is considered owner.

Nonsense dual license combo claim: You cannot just dump `All rights reserved.` in the middle of an MIT license. ARR constitutes a full license of its own. You essentially have two polar opposite licenses shoved together.

(No part of this issue post constitutes formal legal advice.)

**Describe how to be able to reproduce this bug:**

Open the license file at https://github.com/Millenaire/Millenaire/blob/32d46ae711a00031bd540fe2562f1e921ede7854/LICENSE

**Further details:**
- Mod Version: N/A
- Other Mod Versions (Seperated By Commas): N/A
- Forge Version: N/A

- [ ] This issue is High Priority (Crashes the modpack, makes the mod unuseable)
- [ ] I've tested this issue on the latest version of the mod for the latest version of Minecraft.
- [x] I understand that this issue tracker is NOT for the 1.12.2 version of the mod.

**Comment by FireController1847** [comment]
Hey, thanks for pointing this out. I'm no legal expert either, and I kind of just smacked something together to scare off copiers haha! If you know a license that fits these needs below, we'll gladly change it!

You may:
- Fork
- Modify
- Personal Use

You may not:
- Redistribute
- Claim as yours

**Comment by mcmonkey4eva** [comment]
I believe GitHub terms state that any public repo on GitHub is automatically open to the Fork/Modify/Personal set of options regardless of license (excluding illegally uploaded private work, which are subject to lawful takedowns), and specifications outside (such as redistribution or relicensing) that can be set by the exact chosen license.

Essentially, the "You may" you want is fully covered by nature of being on GitHub, and the "You may not" can be restricted as easily as "All Rights Reserved."

I believe you are working from a code base that was originally MIT, which requires the original MIT license notice be retained in any repository containing the code.

What I would go for here (and this, again, does not constitute formal legal advice) is retain an original MIT license (possible in a separate file such as "`ORIGINAL_LICENSE`") that lists the previous owner and the dates it was owned by that owner, and then the main license simply being a standard ARR notice, along the lines of:
`Copyright (c) 2018 Visual Fire Development, All Rights Reserved.`

**Comment by TheTrueColonel** [comment]
We are discussing the license privately. Thank you for the heads up.

**Comment by FireController1847** [comment]
It states 2011-2018 because, while this specific part of this project is only 2018, the entire mod itself dates back to 2011, so we want to keep that within part of the license.

**Comment by mcmonkey4eva** [comment]
You've corrected in that commit one of the problems, disregarded via comment one of the others, but have not at all addressed the third issue: MIT and ARR cannot coexist.

**Comment by FireController1847** [comment]
Eh, it's fine. Thanks for noticing though.

**Comment by mcmonkey4eva** [comment]
If you don't care for making legal sense, you should probably just drop the license file entirely...

**Comment by mdjustin** [comment]
Looking into licensing, the license you would want to use is GNU GPLv3, this license allows the distribution of code, (all other open source licenses also allow the redistribution of the code, it's an unavoidable requirement of the open source nature of the projects).

But GNU also states that all the code that was added or modified to improve/create new or add changes to the original work must be uploaded to a place where it can also be viewed an looked at.  For the nature of this project, this would be the best choice for a project like this. 

https://choosealicense.com/licenses/gpl-3.0/

Source: Have dealt with licensing on many projects over the last 2 years.
