### ISSUE TITLE
Length and width not saved when loading schematics

### ISSUE THREAD

**Issue by MoonCutter2B** [Millenaire/Millenaire#3]
In creative mode I'v managed to load the existing schematics but I had to add saving the length and width values in the BuildingPlan object. They were read but not saved.

in loadSchematic, last line in method:
return new BuildingPlan(culture, level)
				.setHeightDepth(height, depth).setDistance(0, 1).setOrientation(EnumFacing.getHorizontal(2)).setPlan(organized).**setLengthWidth(length, width)**;

**Comment by TheTrueColonel** [comment]
Please fork the repository, and make a branch with the changes, then once finished, make a pull request and the team will evaluate the changes. If they like it, they'll add your code to the repo.

**Comment by MoonCutter2B** [comment]
Think I'v created a pull request for this issue.
